---
- name: Create service account for Accumulo
  user: name=accumulo
        system=yes
        home=/var/lib/accumulo
        shell=/bin/false
        state=present

- name: Download Accumulo packages
  get_url: url="{{ accumulo_mirror }}/accumulo/{{ accumulo_version }}/accumulo-{{ accumulo_version }}-{{ item }}.deb"
           dest="/usr/local/src/accumulo-{{ accumulo_version }}-{{ item }}.deb"
  with_items:
    - bin
    - native

- name: Install Accumulo dependencies
  apt: pkg=g++-multilib state=present

- name: Install Accumulo
  command: "dpkg --ignore-depends=hadoop,zookeeper -i /usr/local/src/accumulo-{{ accumulo_version }}-bin.deb"
  args:
    creates: "{{ accumulo_conf_dir }}"

- name: Install Accumulo native libraries
  command: "dpkg --ignore-depends=hadoop,zookeeper -i /usr/local/src/accumulo-{{ accumulo_version }}-native.deb"
  args:
    creates: "/usr/lib/accumulo/server/src/main/c++"

- name: Fix Accumulo native library post-install script
  lineinfile: dest="/var/lib/dpkg/info/accumulo-native.postinst"
              regexp="^cd /usr/lib/accumulo"
              line="cd /usr/lib/accumulo/server/src/main/c++"
              state=present
  register: fix_accumulo_post_install

- name: Build Accumulo native libraries
  command: dpkg-reconfigure accumulo-native
  args:
    creates: /usr/lib/accumulo/lib/native/map/libNativeMap-Linux-amd64-64.so
  when: fix_accumulo_post_install | changed

- name: Ensure Accumulo directories are owned by Accumulo user
  file: path={{ item }}
        owner=accumulo
        mode=0755
        state=directory
  with_items:
    - "{{ accumulo_log_dir }}/logs"
    - "{{ accumulo_conf_dir }}"

- name: Configure Accumulo service definitions
  template: src=accumulo-{{ item }}.conf.j2
            dest=/etc/init/accumulo-{{ item }}.conf
            mode=0644
  with_items:
    - gc
    - master
    - monitor
    - tracer
    - tserver
